POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço 4",
    "description": "Alguma descrição 4",
    "price": 1800,
    "image": "https://pt.wikipedia.org/wiki/Node.js#/media/Ficheiro:Node.js_logo.svg"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6418466d0aba2425c15b58b3

###
DELETE http://localhost:3000/api/services/6418466d0aba2425c15b58b3

###
PUT http://localhost:3000/api/services/64184990bc497014e943a73f
Content-Type: application/json

{
    "name": "ALGUM SERVIÇO 02",
    "description": "ALGUMA descrição 02",
    "price": 1800,
    "image": "https://pt.wikipedia.org/wiki/Node.js#/media/Ficheiro:Node.js_logo.svg"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 3",
    "author": "João",
    "description": "Uma festa de aniversário",
    "budget": 1000,
    "image": "https://pt.wikipedia.org/wiki/Node.js#/media/Ficheiro:Node.js_logo.svg",
    "services": [
        {
            "name": "ALGUM SERVIÇO 1",
            "description": "ALGUMA descrição 1",
            "price": 3000,
            "image": "https://pt.wikipedia.org/wiki/Node.js#/media/Ficheiro:Node.js_logo.svg"
        },       
        {
            "name": "ALGUM SERVIÇO 2",
            "description": "ALGUMA descrição 2",
            "price": 1600,
            "image": "https://pt.wikipedia.org/wiki/Node.js#/media/Ficheiro:Node.js_logo.svg"
        }   
    ]

}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/641f0453c70bc5885db83884

